SELECT
    EXTRACT(YEAR FROM L_SHIPDATE) AS Year,
    EXTRACT(QUARTER FROM L_SHIPDATE) AS Quarter,
    EXTRACT(MONTH FROM L_SHIPDATE) AS Month,
    N1.N_NAME AS "Exporting nation",
    N2.N_NAME AS "Importing nation",
    SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS Revenue
FROM LINEITEM L
JOIN ORDERS O ON L.L_ORDERKEY = O.O_ORDERKEY
JOIN CUSTOMER C ON O.O_CUSTKEY = C.C_CUSTKEY
JOIN SUPPLIER S ON L.L_SUPPKEY = S.S_SUPPKEY
JOIN NATION N1 ON S.S_NATIONKEY = N1.N_NATIONKEY  
JOIN NATION N2 ON C.C_NATIONKEY = N2.N_NATIONKEY 
WHERE N1.N_NATIONKEY != N2.N_NATIONKEY
GROUP BY ROLLUP(EXTRACT(YEAR FROM L_SHIPDATE), EXTRACT(QUARTER FROM L_SHIPDATE), EXTRACT(MONTH FROM L_SHIPDATE), N1.N_NAME, N2.N_NAME)
ORDER BY Year, Quarter, Month;
