SELECT
    N1.N_NAME AS ExportingNation,
    N2.N_NAME AS ImportingNation,
    R1.R_NAME AS ExportingRegion,
    R2.R_NAME AS ImportingRegion,
    SUM(L.L_EXTENDEDPRICE * (1 - L.L_DISCOUNT)) AS Revenue
FROM LINEITEM L
JOIN ORDERS O ON L.L_ORDERKEY = O.O_ORDERKEY
JOIN CUSTOMER C ON O.O_CUSTKEY = C.C_CUSTKEY
JOIN SUPPLIER S ON L.L_SUPPKEY = S.S_SUPPKEY
JOIN NATION N1 ON S.S_NATIONKEY = N1.N_NATIONKEY  -- Exporting nation
JOIN NATION N2 ON C.C_NATIONKEY = N2.N_NATIONKEY  -- Importing nation
JOIN REGION R1 ON N1.N_REGIONKEY = R1.R_REGIONKEY
JOIN REGION R2 ON N2.N_REGIONKEY = R2.R_REGIONKEY
WHERE N1.N_NATIONKEY != N2.N_NATIONKEY
GROUP BY ROLLUP(N1.N_NAME, N2.N_NAME, R1.R_NAME, R2.R_NAME)
ORDER BY ExportingNation, ImportingNation, ExportingRegion, ImportingRegion;
