CREATE MATERIALIZED VIEW mv_export_import_revenue_region AS
SELECT
    N1.N_NAME AS ExportingNation,
    R1.R_NAME AS ExportingRegion,
    N2.N_NAME AS ImportingNation,
    R2.R_NAME AS ImportingRegion,
    P.P_TYPE AS Type,
    L.L_EXTENDEDPRICE * (1 - L.L_DISCOUNT) AS Revenue
FROM LINEITEM L
JOIN ORDERS O ON L.L_ORDERKEY = O.O_ORDERKEY
JOIN CUSTOMER C ON O.O_CUSTKEY = C.C_CUSTKEY
JOIN SUPPLIER S ON L.L_SUPPKEY = S.S_SUPPKEY
JOIN PART P ON L.L_PARTKEY = P.P_PARTKEY
JOIN NATION N1 ON S.S_NATIONKEY = N1.N_NATIONKEY
JOIN NATION N2 ON C.C_NATIONKEY = N2.N_NATIONKEY
JOIN REGION R1 ON N1.N_REGIONKEY = R1.R_REGIONKEY
JOIN REGION R2 ON N2.N_REGIONKEY = R2.R_REGIONKEY
WHERE N1.N_NATIONKEY != N2.N_NATIONKEY;
--QUERY 
